name: Auto Release

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: Install Pypiwin32
      run: pip install pypiwin32
    - name: Install Requests
      run: pip install requests
    - name: Install Pyinstaller
      run:  pip install pyinstaller
    - name: Write Version File
      run: Set-Content -Path .\version.py -Value "version='$env:CI_COMMIT_SHA'"
    - name: Call Build Script
      run: python.exe .\build.py
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ CI_COMMIT_SHA }}
        release_name: Tabletop Turkeyifier v${{ CI_COMMIT_SHA }}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/tabletop-turkeyifier.exe
        asset_name: tabletop-turkeyifier.exe
        asset_content_type: application/exe
