name: Auto Release

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: Build Project
      run: |
        echo installing required packages
        pip install requests
        pip install pyinstaller
        echo building project
        echo version = "$env:CI_COMMIT_SHA">version.py
        python.exe .\build.py

